{% set name = "splink" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60ada5c9d24e905758c4472c650ce8d095ca5ca70375da4901de6d0c43d0c217

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry
  run:
    - python >=3.6,<4.0
    - jsonschema
    - pyspark
    - typeguard
test:
  imports:
    - splink

about:
  home: https://github.com/moj-analytical-services/splink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Implements Fellegi-Sunter's canonical model of record linkage in Apache Spark, including EM algorithm to estimate parameters of the model

extra:
  recipe-maintainers:
    - cdesouza21
