{% set name = "splink" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e72edb7c8b43a933c83f7e879a15107f3bd78c12bdb7fb9fb4c7ad1bdef0bc97

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.7,<4.0
    - jsonschema >=3.2,<5.0
    - python-duckdb >=0.6.0,<0.7.0
    - pandas >=1.0.0,<2.0.0
    - sqlglot >=5.1.0
    - altair >=4.2.0
    - jinja2 >=3.0.3,<4.0.0
  run_constrained:
    - pyspark >=3.2.1

test:
  imports:
    - splink

about:
  home: https://github.com/moj-analytical-services/splink
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast, accurate and scalable probabilistic data linkage using your choice of SQL backend.
  doc_url: https://moj-analytical-services.github.io/splink/

extra:
  recipe-maintainers:
    - ThomasHepworth
    - ADBond
    - cdesouza21
